"""First commit

Revision ID: 9be69de08946
Revises: 
Create Date: 2023-10-19 17:37:35.883015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be69de08946'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlight_source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startMeta', sa.JSON(), nullable=True),
    sa.Column('endMeta', sa.JSON(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highlight_source')
    # ### end Alembic commands ###
