"""First commit

Revision ID: b1f27549028d
Revises: 
Create Date: 2023-11-13 14:15:11.137807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f27549028d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HIGHLIGHTS',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start_meta', sa.JSON(), nullable=True),
    sa.Column('end_meta', sa.JSON(), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('annotation_tag', sa.Enum('Strength', 'Weakness', 'ActionItem', 'Confused', 'Other', name='annotationtag'), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ACTIONS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('actionpoint', sa.Enum('FurtherPractice', 'ContactTutor', 'ReferLearningResources', name='actionpointcategory'), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('annotation_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['annotation_id'], ['HIGHLIGHTS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ACTIONS')
    op.drop_table('HIGHLIGHTS')
    # ### end Alembic commands ###
