"""highlight table

Revision ID: b6aaaa4751e1
Revises: 
Create Date: 2023-11-16 00:53:25.146033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6aaaa4751e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HIGHLIGHTS',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('startMeta', sa.JSON(), nullable=True),
    sa.Column('endMeta', sa.JSON(), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('annotationTag', sa.Enum('Strength', 'Weakness', 'ActionItem', 'Confused', 'Other', name='annotationtag'), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ACTIONS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('actionPoint', sa.Enum('FurtherPractice', 'ContactTutor', 'ReferLearningResources', name='actionpointcategory'), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('annotationId', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['annotationId'], ['HIGHLIGHTS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ACTIONS')
    op.drop_table('HIGHLIGHTS')
    # ### end Alembic commands ###
